<div class="container" style="padding-top: 150px;">
    <div class="row">
        <ul class="list-group">
            <li class="list-group-item">
                <span class="badge" style="">1.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic4.jpg" alt="Малък дюнер" title="Малък дюнер"/>
                <span>Малък дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">2.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic5.jpg" alt="Среден дюнер" title="Среден дюнер"/>
                <span>Среден дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">4.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic6.jpg" alt="Голям дюнер" title="Голям дюнер"/>
                <span>Голям дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">1.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic4.jpg" alt="Малък дюнер" title="Малък дюнер"/>
                <span>Малък дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">2.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic5.jpg" alt="Среден дюнер" title="Среден дюнер"/>
                <span>Среден дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">4.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic6.jpg" alt="Голям дюнер" title="Голям дюнер"/>
                <span>Голям дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">1.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic4.jpg" alt="Малък дюнер" title="Малък дюнер"/>
                <span>Малък дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">2.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic5.jpg" alt="Среден дюнер" title="Среден дюнер"/>
                <span>Среден дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">4.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic6.jpg" alt="Голям дюнер" title="Голям дюнер"/>
                <span>Голям дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">1.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic4.jpg" alt="Малък дюнер" title="Малък дюнер"/>
                <span>Малък дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">2.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic5.jpg" alt="Среден дюнер" title="Среден дюнер"/>
                <span>Среден дюнер</span>
            </li>
            <li class="list-group-item">
                <span class="badge" style="">4.50лв</span>
                <img style="display: inline !important;" class="img-rounded img-responsive" src="../img/f_pic6.jpg" alt="Голям дюнер" title="Голям дюнер"/>
                <span>Голям дюнер</span>
            </li>
        </ul>
    </div>
</div>