<div class="container-fluid footer-bckgr text-primary">
    <div class="row" style="border-bottom: 1px solid #f53300; padding: 20px 0;">
        <div class="col-sm-8">
            <a href="#" class="facebook">facebook</a>
            <a href="#" class="youtube">youtube</a>
        </div>
        <div class="col-sm-4">
            За контакти +359883333333
        </div>
    </div>
    <div class="row">
        <div class="text-center" style="padding: 20px 0;">
            <div class="col-sm-12 copy">&copy; Brzilia <?php echo date('Y') ?> <?php echo $this->translate('All rights reserved.') ?> Developed by <a href="http://www.scholak.com/">scholak</a></div>
        </div>
    </div>
</div>