<div class="container-fluid">
    <nav class="navbar navbar-default navbar-fixed-top header" role="navigation">
        <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3 pull-right text-muted text-center">За връзка 24/7: +44 123 456 7891</div>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#brzilia-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img alt="Brand" title="Brand" src="<?php echo $this->basePath('img/logo.png') ?>"/>
            </a>
        </div>
        <?php
        $active = 'class="active"';
        $currControllerName = $this->controllerName();
        ?>
        <div class="collapse navbar-collapse navbar-right" id="brzilia-navbar-collapse">
            <?php
//            echo $this->navigation('navigation')
//                    ->menu()
//                    ->setMinDepth(0)
//                    ->setMaxDepth(0)
//                    ->setUlClass('nav navbar-nav');
            ?>
            <ul class="nav navbar-nav">
                <li <?php echo $currControllerName == "Brzilia\Controller\Index" ? $active : ''; ?>><a href="<?php echo $this->url('home', array('controller' => 'index', 'action' => 'index')); ?>">Начало <span class="sr-only">(current)</span></a></li>
                <li <?php echo $currControllerName == "Brzilia\Controller\Menu" ? $active : ''; ?>><a href="<?php echo $this->url('brzilia', array('controller' => 'menu', 'action' => 'index')); ?>">Меню</a></li>
                <li <?php echo $currControllerName == "Brzilia\Controller\About" ? $active : ''; ?>><a href="<?php echo $this->url('brzilia', array('controller' => 'about', 'action' => 'index')); ?>">За нас</a></li>
                <li style="padding-right: 20px;">&nbsp;</li>
            </ul>
        </div>
    </nav>
</div>
