<div class="container" style="padding-top: 50px;">
    <div class="row">
        <div class="col-sm-4">&nbsp;</div>
        <div class="col-sm-4">
            <h1><?php echo $this->translate('Грешка 404') ?></h1>
            <p class="text-center"><img src="<?php echo $this->basePath('img/pagenotfound.jpg'); ?>" alt="Page not found" title="Page not found" /></p>
        </div>
        <div class="col-sm-4">&nbsp;</div>
    </div>
</div>
