<div class="container-fluid">
    <div class="row" style="margin-top: 75px;">
        <div id="carousel-brz-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-brz-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-brz-generic" data-slide-to="1" class="active"></li>
                <li data-target="#carousel-brz-generic" data-slide-to="2" class="active"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="<?php echo $this->basePath('img/slider1.jpg'); ?>" alt="Slider1" title="Slider1"/>
                    <div class="carousel-caption">
                        Slider1
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slider2.jpg'); ?>" alt="Slider2" title="Slider2" />
                    <div class="carousel-caption">
                        Slider2
                    </div>
                </div>
                <div class="item">
                    <img src="<?php echo $this->basePath('img/slider3.jpg'); ?>" alt="Slider3" title="Slider3" />
                    <div class="carousel-caption">
                        Slider3
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-brz-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-brz-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="row" style="">
        <div class="col-sm-3">
            <img class="img-responsive" style="display: block;margin: 0 auto;" src="<?php echo $this->basePath('img/pic1.jpg'); ?>"  alt="first" title="first" />
            <div class="arrow-top">
                <a href="#" class="title-box-home">salads can be light & healthy</a>
                <h4>looking for quality salad receipes?</h4>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. when an unknown printer took a galley of type and scrambled it to make specimen book.</p>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="arrow-bottom">
                <a href="#" class="title-box-home">here you can find beauty deserts!</a>
                <h4>looking for quality salad receipes?</h4>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</p>
            </div>
            <img class="img-responsive" style="display: block;margin: 0 auto;" src="<?php echo $this->basePath('img/pic2.jpg'); ?>"  alt="second" title="second" />
        </div>
        <div class="col-sm-3 ">
            <img class="img-responsive" style="display: block;margin: 0 auto;" src="<?php echo $this->basePath('img/pic3.jpg'); ?>" alt="third" title="third" />
            <div class="arrow-top">
                <a href="#" class="title-box-home">strawberry deserts design</a>
                <h4>looking for quality salad receipes?</h4>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever</p>
            </div>
        </div>
        <div class="col-sm-3 col4-bckgr">
            <h3 class="text-center">Топ оферти</h3>
            <ul class="list-group" style="//color: #FFF; font-weight: bold">
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
                <li class="list-group-item">Малък дюнер <span class="badge">1.50лв</span></li>
            </ul>
        </div>
    </div>
</div>